import type {
  PartnerWorkspace,
  PartnerStatus,
  PartnerChannel,
  DealStage,
  DocumentKind,
  DocumentStatus,
  ScheduleKind,
  ScheduleStatus,
  AutomationStatus,
} from "./partners-types"

function status<T extends string>(value: T) {
  return value
}

const partnerStatus = (value: PartnerStatus) => status(value)
const partnerChannel = (value: PartnerChannel) => status(value)
const dealStage = (value: DealStage) => status(value)
const documentKind = (value: DocumentKind) => status(value)
const documentStatus = (value: DocumentStatus) => status(value)
const scheduleKind = (value: ScheduleKind) => status(value)
const scheduleStatus = (value: ScheduleStatus) => status(value)
const automationStatus = (value: AutomationStatus) => status(value)

export const partnerWorkspaces: PartnerWorkspace[] = [
  {
    partner: {
      id: "mirae-academy",
      name: "미래아카데미",
      status: partnerStatus("active"),
      channel: partnerChannel("reseller"),
      region: "서울 강남",
      ownerName: "김지훈",
      ownerEmail: "jhkim@mirae-academy.kr",
      accountManager: "정소연",
      nextActionAt: "2026-04-08 14:00",
      tags: ["활성", "전자칠판", "재계약 후보"],
      notes: "4월 2주차 데모 이후 추가 견적 요청 대기 상태입니다.",
    },
    deals: [
      {
        id: "deal_mirae_1",
        partnerId: "mirae-academy",
        title: "2026 상반기 전자칠판 패키지",
        stage: dealStage("contract_sent"),
        quoteAmount: 18500000,
        expectedCloseAt: "2026-04-12",
        contractStartAt: "2026-05-01",
        contractEndAt: "2027-04-30",
        salesUnits: 12,
        manager: "정소연",
      },
      {
        id: "deal_mirae_2",
        partnerId: "mirae-academy",
        title: "기존 설치 지점 유지보수",
        stage: dealStage("active"),
        quoteAmount: 4200000,
        contractStartAt: "2026-03-01",
        contractEndAt: "2026-12-31",
        salesUnits: 0,
        manager: "정소연",
      },
    ],
    documents: [
      {
        id: "doc_mirae_quote_1",
        partnerId: "mirae-academy",
        dealId: "deal_mirae_1",
        kind: documentKind("quote"),
        status: documentStatus("sent"),
        title: "Q-2026-041 미래아카데미 패키지 견적서",
        amount: 18500000,
        issuedAt: "2026-04-02",
        dueAt: "2026-04-09",
        fileLabel: "견적서 v2.pdf",
      },
      {
        id: "doc_mirae_contract_1",
        partnerId: "mirae-academy",
        dealId: "deal_mirae_1",
        kind: documentKind("contract"),
        status: documentStatus("draft"),
        title: "2026 상반기 공급 계약서",
        issuedAt: "2026-04-03",
        fileLabel: "계약서 초안.docx",
      },
      {
        id: "doc_mirae_receipt_1",
        partnerId: "mirae-academy",
        dealId: "deal_mirae_2",
        kind: documentKind("receipt"),
        status: documentStatus("paid"),
        title: "3월 유지보수 영수증",
        amount: 350000,
        issuedAt: "2026-03-31",
        fileLabel: "3월 영수증.pdf",
      },
    ],
    schedule: [
      {
        id: "sch_mirae_1",
        partnerId: "mirae-academy",
        dealId: "deal_mirae_1",
        kind: scheduleKind("follow_up"),
        status: scheduleStatus("planned"),
        title: "견적서 확인 후속 전화",
        startsAt: "2026-04-08 14:00",
        owner: "정소연",
      },
      {
        id: "sch_mirae_2",
        partnerId: "mirae-academy",
        kind: scheduleKind("meeting"),
        status: scheduleStatus("planned"),
        title: "현장 설치 범위 점검 미팅",
        startsAt: "2026-04-10 11:00",
        endsAt: "2026-04-10 12:00",
        owner: "정소연",
      },
      {
        id: "sch_mirae_3",
        partnerId: "mirae-academy",
        dealId: "deal_mirae_2",
        kind: scheduleKind("deadline"),
        status: scheduleStatus("planned"),
        title: "4월 유지보수 정산 마감",
        startsAt: "2026-04-30 18:00",
        owner: "김서준",
      },
    ],
    sales: [
      {
        id: "sales_mirae_2026_02",
        partnerId: "mirae-academy",
        dealId: "deal_mirae_2",
        salesMonth: "2026-02-01",
        unitsSold: 6,
        grossAmount: 9900000,
        netAmount: 8800000,
      },
      {
        id: "sales_mirae_2026_03",
        partnerId: "mirae-academy",
        dealId: "deal_mirae_2",
        salesMonth: "2026-03-01",
        unitsSold: 8,
        grossAmount: 12400000,
        netAmount: 11200000,
      },
    ],
    automations: [
      {
        id: "auto_mirae_1",
        partnerId: "mirae-academy",
        name: "견적 만료 24시간 전 알림",
        status: automationStatus("active"),
        trigger: "quote.due_at - 24h",
        action: "담당자 슬랙 알림 + 후속 일정 생성",
        destination: "Slack / Calendar",
        lastRunAt: "2026-04-02 09:00",
        nextRunAt: "2026-04-08 09:00",
      },
      {
        id: "auto_mirae_2",
        partnerId: "mirae-academy",
        name: "월말 판매 집계",
        status: automationStatus("active"),
        trigger: "매월 말 18:00",
        action: "판매 댓수 합산 후 리포트 전송",
        destination: "Email / Notion",
        lastRunAt: "2026-03-31 18:00",
        nextRunAt: "2026-04-30 18:00",
      },
    ],
  },
  {
    partner: {
      id: "alpha-branch",
      name: "알파지사 유통",
      status: partnerStatus("churn_risk"),
      channel: partnerChannel("branch"),
      region: "부산 해운대",
      ownerName: "박현우",
      ownerEmail: "hwpark@alpha-branch.kr",
      accountManager: "김서준",
      nextActionAt: "2026-04-05 10:30",
      tags: ["정산지연", "재협상", "지사"],
      notes: "2월분 영수증 누락으로 정산 지연. 계약 갱신 전 정리 필요.",
    },
    deals: [
      {
        id: "deal_alpha_1",
        partnerId: "alpha-branch",
        title: "2025-2026 지사 공급 계약",
        stage: dealStage("active"),
        quoteAmount: 24000000,
        contractStartAt: "2025-09-01",
        contractEndAt: "2026-08-31",
        salesUnits: 19,
        manager: "김서준",
      },
      {
        id: "deal_alpha_2",
        partnerId: "alpha-branch",
        title: "여름 특강 단기 추가 공급",
        stage: dealStage("quoted"),
        quoteAmount: 5600000,
        expectedCloseAt: "2026-04-18",
        salesUnits: 4,
        manager: "김서준",
      },
    ],
    documents: [
      {
        id: "doc_alpha_contract_1",
        partnerId: "alpha-branch",
        dealId: "deal_alpha_1",
        kind: documentKind("contract"),
        status: documentStatus("signed"),
        title: "2025-2026 지사 공급 계약서",
        issuedAt: "2025-08-20",
        fileLabel: "alpha-branch-contract.pdf",
      },
      {
        id: "doc_alpha_receipt_1",
        partnerId: "alpha-branch",
        dealId: "deal_alpha_1",
        kind: documentKind("receipt"),
        status: documentStatus("overdue"),
        title: "2월 매출 정산 영수증",
        amount: 980000,
        issuedAt: "2026-03-05",
        dueAt: "2026-03-12",
        fileLabel: "2026-02-receipt.pdf",
      },
      {
        id: "doc_alpha_quote_1",
        partnerId: "alpha-branch",
        dealId: "deal_alpha_2",
        kind: documentKind("quote"),
        status: documentStatus("draft"),
        title: "여름 특강 추가 공급 견적서",
        amount: 5600000,
        issuedAt: "2026-04-01",
        fileLabel: "summer-program-quote.xlsx",
      },
    ],
    schedule: [
      {
        id: "sch_alpha_1",
        partnerId: "alpha-branch",
        kind: scheduleKind("deadline"),
        status: scheduleStatus("planned"),
        title: "2월 영수증 보완 제출 마감",
        startsAt: "2026-04-05 10:30",
        owner: "김서준",
      },
      {
        id: "sch_alpha_2",
        partnerId: "alpha-branch",
        dealId: "deal_alpha_2",
        kind: scheduleKind("meeting"),
        status: scheduleStatus("planned"),
        title: "추가 공급 범위 조정 회의",
        startsAt: "2026-04-09 15:00",
        endsAt: "2026-04-09 16:00",
        owner: "김서준",
      },
    ],
    sales: [
      {
        id: "sales_alpha_2026_01",
        partnerId: "alpha-branch",
        dealId: "deal_alpha_1",
        salesMonth: "2026-01-01",
        unitsSold: 11,
        grossAmount: 14800000,
        netAmount: 13100000,
      },
      {
        id: "sales_alpha_2026_02",
        partnerId: "alpha-branch",
        dealId: "deal_alpha_1",
        salesMonth: "2026-02-01",
        unitsSold: 8,
        grossAmount: 11200000,
        netAmount: 9600000,
      },
    ],
    automations: [
      {
        id: "auto_alpha_1",
        partnerId: "alpha-branch",
        name: "연체 영수증 리마인드",
        status: automationStatus("active"),
        trigger: "receipt.status = overdue",
        action: "담당자 메일 + 3일 후 재알림 예약",
        destination: "Email / Calendar",
        lastRunAt: "2026-04-01 09:30",
        nextRunAt: "2026-04-04 09:30",
      },
    ],
  },
  {
    partner: {
      id: "jeju-edu",
      name: "제주에듀파트너",
      status: partnerStatus("lead"),
      channel: partnerChannel("referral"),
      region: "제주 제주시",
      ownerName: "이아름",
      ownerEmail: "areum@jeju-edu.kr",
      accountManager: "유민정",
      nextActionAt: "2026-04-11 13:00",
      tags: ["신규", "추천유입", "체험중"],
      notes: "3개월 체험 후 정식 견적 전환 예정입니다.",
    },
    deals: [
      {
        id: "deal_jeju_1",
        partnerId: "jeju-edu",
        title: "파일럿 체험 패키지",
        stage: dealStage("discovery"),
        quoteAmount: 0,
        expectedCloseAt: "2026-04-25",
        salesUnits: 0,
        manager: "유민정",
      },
    ],
    documents: [
      {
        id: "doc_jeju_quote_1",
        partnerId: "jeju-edu",
        dealId: "deal_jeju_1",
        kind: documentKind("quote"),
        status: documentStatus("draft"),
        title: "체험 종료 후 본견적 예정",
        fileLabel: "견적 준비중",
      },
    ],
    schedule: [
      {
        id: "sch_jeju_1",
        partnerId: "jeju-edu",
        kind: scheduleKind("meeting"),
        status: scheduleStatus("planned"),
        title: "체험 결과 리뷰 미팅",
        startsAt: "2026-04-11 13:00",
        endsAt: "2026-04-11 14:00",
        owner: "유민정",
      },
      {
        id: "sch_jeju_2",
        partnerId: "jeju-edu",
        kind: scheduleKind("renewal"),
        status: scheduleStatus("planned"),
        title: "체험 종료 후 견적 전환 판단",
        startsAt: "2026-04-25 17:00",
        owner: "유민정",
      },
    ],
    sales: [],
    automations: [
      {
        id: "auto_jeju_1",
        partnerId: "jeju-edu",
        name: "체험 종료 리마인드",
        status: automationStatus("paused"),
        trigger: "trial.ends_at - 3d",
        action: "후속 견적 생성 초안 준비",
        destination: "Slack / Notion",
        nextRunAt: "2026-04-22 10:00",
      },
    ],
  },
]

export function listPartnerWorkspaces() {
  return partnerWorkspaces
}

export function getPartnerWorkspace(id: string) {
  return partnerWorkspaces.find((workspace) => workspace.partner.id === id)
}
