/**
 * region_aliases 시드 SQL 생성기.
 *
 * lib/regions/korea-regions.ts 를 단일 진실 원천으로, region_aliases UPSERT SQL을
 * stdout 으로 출력한다. lib 의 시도 이형/시군구 매핑이 바뀌면 아래로 재생성한다:
 *
 *   npx tsx scripts/seed-region-aliases.ts > supabase/migrations/20260621_regions_reference_seed.sql
 */
import { buildRegionAliasSeed } from "../lib/regions/korea-regions"

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function main(): void {
  const rows = buildRegionAliasSeed()
  const values = rows
    .map(
      (r) =>
        `  (${sqlString(r.alias)}, ${sqlString(r.normalized)}, ${sqlString(r.regionCode)}, ${sqlString(r.kind)})`,
    )
    .join(",\n")

  const sql = `-- AUTO-GENERATED by scripts/seed-region-aliases.ts — DO NOT EDIT BY HAND.
-- 원천: lib/regions/korea-regions.ts (buildRegionAliasSeed). 재생성하려면 스크립트를 다시 실행.
-- region_aliases 시드: 시도 이형 + 시군구 약식 총 ${rows.length}개 행.

INSERT INTO public.region_aliases (alias, normalized, region_code, kind) VALUES
${values}
ON CONFLICT (normalized) DO UPDATE SET
  alias       = EXCLUDED.alias,
  region_code = EXCLUDED.region_code,
  kind        = EXCLUDED.kind;
`
  process.stdout.write(sql)
}

main()
